name: Build
on: [ push ]
jobs:
  build:
    name: Build Docker image 
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build
        run: make build
      - name: Test
        env:
          TIDAL_TOKEN: ${{ secrets.TIDAL_TOKEN }}
        run: make test